import { spawnSync } from "node:child_process";
import { createHash } from "node:crypto";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";

const AUTH_FILE = "auth.json";
const CONFIG_FILE = "config.toml";
const SOURCE_HASH_FILE = ".source-auth.sha256";
const DEFAULT_SECRET_NAME = "CODEX_AUTH_JSON";

export interface PrepareSubscriptionAuthOptions {
	authJson: string;
	codexHome: string;
	githubEnvPath?: string;
}

export interface RefreshSubscriptionAuthOptions {
	codexHome: string;
	repository: string;
	secretName?: string;
	githubToken: string;
	setSecret?: (
		authJson: string,
		repository: string,
		secretName: string,
		githubToken: string,
	) => void;
}

function validateAuthJson(authJson: string): string {
	const trimmed = authJson.trim();
	if (!trimmed) throw new Error("Codex subscription auth is empty.");

	const parsed: unknown = JSON.parse(trimmed);
	if (typeof parsed !== "object" || parsed === null || Array.isArray(parsed)) {
		throw new Error("Codex subscription auth must be a JSON object.");
	}

	return `${trimmed}\n`;
}

function validateCodexHome(codexHome: string): string {
	if (!path.isAbsolute(codexHome)) {
		throw new Error("CONDUCTOR_CODEX_HOME must be an absolute path.");
	}
	if (codexHome.includes("\n") || codexHome.includes("\r")) {
		throw new Error("CONDUCTOR_CODEX_HOME cannot contain newlines.");
	}
	return path.resolve(codexHome);
}

function isWithin(candidate: string, parent: string): boolean {
	const relative = path.relative(path.resolve(parent), candidate);
	return (
		relative === "" ||
		(!relative.startsWith("..") && !path.isAbsolute(relative))
	);
}

function assertCredentialHomeIsNotTemporary(codexHome: string): void {
	const tempRoots = [
		process.env.RUNNER_TEMP,
		process.env.TMPDIR,
		os.tmpdir(),
		"/tmp",
		"/private/tmp",
	].filter((value): value is string => Boolean(value));
	const unsafeRoot = tempRoots.find((root) => isWithin(codexHome, root));
	if (unsafeRoot) {
		throw new Error(
			`CONDUCTOR_CODEX_HOME cannot be inside writable temporary root ${unsafeRoot}.`,
		);
	}
}

function validateRepository(repository: string): string {
	const valid = /^[A-Za-z0-9_.-]+\/[A-Za-z0-9_.-]+$/.test(repository);
	if (!valid) {
		throw new Error("CODEX_CREDENTIAL_REPOSITORY must be OWNER/REPO.");
	}
	return repository;
}

function authHash(authJson: string): string {
	return createHash("sha256").update(authJson).digest("hex");
}

function setGitHubSecret(
	authJson: string,
	repository: string,
	secretName: string,
	githubToken: string,
): void {
	const result = spawnSync(
		"gh",
		["secret", "set", secretName, "--repo", repository],
		{
			encoding: "utf8",
			input: authJson,
			env: {
				PATH: process.env.PATH,
				HOME: process.env.HOME,
				GH_TOKEN: githubToken,
			},
		},
	);

	if (result.status !== 0) {
		throw new Error(
			`Failed to persist refreshed Codex subscription auth: ${(
				result.stderr || result.stdout || "gh secret set failed"
			).trim()}`,
		);
	}
}

function tomlString(value: string): string {
	return JSON.stringify(value);
}

export function buildSubscriptionCodexConfig(codexHome: string): string {
	const protectedHome = validateCodexHome(codexHome);
	return `# Generated by Conductor. Commands run by Codex cannot read this directory.
cli_auth_credentials_store = "file"
default_permissions = "conductor-worker"
approval_policy = "never"

[permissions.conductor-worker]
description = "Write the target workspace while isolating subscription credentials."
extends = ":workspace"

[permissions.conductor-worker.filesystem]
":root" = "deny"
":minimal" = "read"
":tmpdir" = "write"
":slash_tmp" = "write"
${tomlString(protectedHome)} = "deny"

[permissions.conductor-worker.network]
enabled = true

[permissions.conductor-worker.network.domains]
"*" = "allow"
`;
}

export function prepareSubscriptionAuth(
	options: PrepareSubscriptionAuthOptions,
): string {
	const codexHome = validateCodexHome(options.codexHome);
	assertCredentialHomeIsNotTemporary(codexHome);
	const authJson = validateAuthJson(options.authJson);

	fs.mkdirSync(codexHome, { recursive: true, mode: 0o700 });
	fs.chmodSync(codexHome, 0o700);
	fs.writeFileSync(path.join(codexHome, AUTH_FILE), authJson, { mode: 0o600 });
	fs.writeFileSync(
		path.join(codexHome, CONFIG_FILE),
		buildSubscriptionCodexConfig(codexHome),
		{ mode: 0o600 },
	);
	fs.writeFileSync(path.join(codexHome, SOURCE_HASH_FILE), authHash(authJson), {
		mode: 0o600,
	});

	if (options.githubEnvPath) {
		fs.appendFileSync(options.githubEnvPath, `CODEX_HOME=${codexHome}\n`);
	}

	return codexHome;
}

export function refreshSubscriptionAuth(
	options: RefreshSubscriptionAuthOptions,
): boolean {
	const codexHome = validateCodexHome(options.codexHome);
	const repository = validateRepository(options.repository);
	const authPath = path.join(codexHome, AUTH_FILE);
	const sourceHashPath = path.join(codexHome, SOURCE_HASH_FILE);
	const authJson = validateAuthJson(fs.readFileSync(authPath, "utf8"));
	const currentHash = authHash(authJson);
	const sourceHash = fs.readFileSync(sourceHashPath, "utf8").trim();

	if (currentHash === sourceHash) return false;

	const secretName = options.secretName || DEFAULT_SECRET_NAME;
	const setSecret = options.setSecret || setGitHubSecret;
	setSecret(authJson, repository, secretName, options.githubToken);

	fs.writeFileSync(sourceHashPath, currentHash, { mode: 0o600 });
	return true;
}

function resolveCodexHome(): string {
	if (process.env.CONDUCTOR_CODEX_HOME) {
		return process.env.CONDUCTOR_CODEX_HOME;
	}

	const home = process.env.HOME;
	if (!home) {
		throw new Error("Set CONDUCTOR_CODEX_HOME or HOME.");
	}

	const runId = process.env.GITHUB_RUN_ID || "local";
	const attempt = process.env.GITHUB_RUN_ATTEMPT || "1";
	return path.join(home, ".conductor-codex", `${runId}-${attempt}`);
}

function main(): void {
	const command = process.argv[2];
	if (command === "prepare") {
		const authJson = process.env.CODEX_AUTH_JSON;
		if (!authJson) throw new Error("CODEX_AUTH_JSON is required.");
		const codexHome = prepareSubscriptionAuth({
			authJson,
			codexHome: resolveCodexHome(),
			githubEnvPath: process.env.GITHUB_ENV,
		});
		process.stdout.write(
			`Prepared isolated Codex subscription auth at ${codexHome}.\n`,
		);
		return;
	}

	if (command === "refresh") {
		const repository = process.env.CODEX_CREDENTIAL_REPOSITORY;
		const githubToken = process.env.CODEX_CREDENTIALS_WRITE_TOKEN;
		if (!repository) {
			throw new Error("CODEX_CREDENTIAL_REPOSITORY is required.");
		}
		if (!githubToken) {
			throw new Error("CODEX_CREDENTIALS_WRITE_TOKEN is required.");
		}
		const updated = refreshSubscriptionAuth({
			codexHome: resolveCodexHome(),
			repository,
			secretName: process.env.CODEX_AUTH_SECRET_NAME,
			githubToken,
		});
		process.stdout.write(
			updated
				? "Persisted refreshed Codex subscription auth.\n"
				: "Codex subscription auth did not change; no writeback needed.\n",
		);
		return;
	}

	throw new Error("Usage: codex-subscription-auth <prepare|refresh>");
}

if (require.main === module) {
	try {
		main();
	} catch (error) {
		process.stderr.write(
			`${error instanceof Error ? error.message : String(error)}\n`,
		);
		process.exit(1);
	}
}
